name: Generate tweet

on:
  workflow_dispatch:

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "node" # Use the latest Node.js version

        # Install dependencies if package.json exists
      - name: Install dependencies
        run: |
          npm install

      # Inject secrets as environment variables
      - name: Run Node.js Script with Env Variables
        run: |
          npm start
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          GLIF_API_TOKEN: ${{ secrets.GLIF_API_TOKEN }}
          GLIF_API_TOKEN2: ${{ secrets.GLIF_API_TOKEN2 }}
